# Generated by Django 3.2.8 on 2021-10-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20211020_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='pause_state',
            field=models.CharField(choices=[('paused', 'pause'), ('running', 'Unpause')], default='paused', max_length=32),
        ),
    ]
